token_registry/lib/token_registry_web/router.ex
defmodule TokenRegistryWeb.Router do
  use TokenRegistryWeb, :router

  import TokenRegistryWeb.UserAuth

  import Phoenix.LiveView.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TokenRegistryWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TokenRegistryWeb do
    pipe_through :browser

    live "/",  PageLive, :index
    # live "/",TokenLive.Index, :index #
  end

  # Other scopes may use custom stacks.
  # scope "/api", TokenRegistryWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TokenRegistryWeb.Telemetry
    end
  end

  ## Authentication routes


  scope "/api", TokenRegistryWeb do
    pipe_through [:api]

    resources "/blockchains", BlockchainController, except: [:new, :edit]
    resources "/tokens", TokenController, except: [:new, :edit]
  end

  scope "/", TokenRegistryWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", TokenRegistryWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", TokenRegistryWeb do
    pipe_through [:browser, :require_authenticated_user]




  live "/blockchains", BlockchainLive.Index, :index
  live "/blockchains/new", BlockchainLive.Index, :new
  live "/blockchains/:id/edit", BlockchainLive.Index, :edit

  live "/blockchains/:id", BlockchainLive.Show, :show
  live "/blockchains/:id/show/edit", BlockchainLive.Show, :edit
end

  scope "/", TokenRegistryWeb do
    pipe_through [:browser]



    live "/tokens", TokenLive.Index, :index
    live "/tokens/new", TokenLive.Index, :new
    live "/tokens/:id/edit", TokenLive.Index, :edit

    live "/tokens/:id", TokenLive.Show, :show
    live "/tokens/:id/show/edit", TokenLive.Show, :edit
  end

  scope "/", TokenRegistryWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

token_registry/lib/token_registry_web/live/blockchain_live/form_component.ex
defmodule TokenRegistryWeb.BlockchainLive.FormComponent do
  use TokenRegistryWeb, :live_component

  alias TokenRegistry.Registry

  @impl true
  def update(%{blockchain: blockchain} = assigns, socket) do
    changeset = Registry.change_blockchain(blockchain)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"blockchain" => blockchain_params}, socket) do
    changeset =
      socket.assigns.blockchain
      |> Registry.change_blockchain(blockchain_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"blockchain" => blockchain_params}, socket) do
    save_blockchain(socket, socket.assigns.action, blockchain_params)
  end

  defp save_blockchain(socket, :edit, blockchain_params) do
    case Registry.update_blockchain(socket.assigns.blockchain, blockchain_params) do
      {:ok, _blockchain} ->
        {:noreply,
         socket
         |> put_flash(:info, "Blockchain updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_blockchain(socket, :new, blockchain_params) do
    case Registry.create_blockchain(blockchain_params) do
      {:ok, _blockchain} ->
        {:noreply,
         socket
         |> put_flash(:info, "Blockchain created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

token_registry/lib/token_registry_web/live/blockchain_live/index.ex
defmodule TokenRegistryWeb.BlockchainLive.Index do
  use TokenRegistryWeb, :live_view

  alias TokenRegistry.Registry
  alias TokenRegistry.Registry.Blockchain

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :blockchains, list_blockchains())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Blockchain")
    |> assign(:blockchain, Registry.get_blockchain!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Blockchain")
    |> assign(:blockchain, %Blockchain{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Blockchains")
    |> assign(:blockchain, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    blockchain = Registry.get_blockchain!(id)
    {:ok, _} = Registry.delete_blockchain(blockchain)

    {:noreply, assign(socket, :blockchains, list_blockchains())}
  end

  defp list_blockchains do
    Registry.list_blockchains()
  end
end

token_registry/lib/token_registry_web/live/blockchain_live/show.ex
defmodule TokenRegistryWeb.BlockchainLive.Show do
  use TokenRegistryWeb, :live_view

  alias TokenRegistry.Registry

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:blockchain, Registry.get_blockchain!(id))}
  end

  defp page_title(:show), do: "Show Blockchain"
  defp page_title(:edit), do: "Edit Blockchain"
end

token_registry/lib/token_registry_web/live/live_helpers.ex
defmodule TokenRegistryWeb.LiveHelpers do
  import Phoenix.LiveView.Helpers

  @doc """
  Renders a component inside the `TokenRegistryWeb.ModalComponent` component.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <%= live_modal @socket, TokenRegistryWeb.TokenLive.FormComponent,
        id: @token.id || :new,
        action: @live_action,
        token: @token,
        return_to: Routes.token_index_path(@socket, :index) %>
  """
  def live_modal(socket, component, opts) do
    path = Keyword.fetch!(opts, :return_to)
    modal_opts = [id: :modal, return_to: path, component: component, opts: opts]
    live_component(socket, TokenRegistryWeb.ModalComponent, modal_opts)
  end
end

token_registry/lib/token_registry_web/live/modal_component.ex
defmodule TokenRegistryWeb.ModalComponent do
  use TokenRegistryWeb, :live_component

  @impl true
  def render(assigns) do
    ~L"""
    <div id="<%= @id %>" class="phx-modal"
      phx-capture-click="close"
      phx-window-keydown="close"
      phx-key="escape"
      phx-target="#<%= @id %>"
      phx-page-loading>

      <div class="phx-modal-content">
        <%= live_patch raw("&times;"), to: @return_to, class: "phx-modal-close" %>
        <%= live_component @socket, @component, @opts %>
      </div>
    </div>
    """
  end

  @impl true
  def handle_event("close", _, socket) do
    {:noreply, push_patch(socket, to: socket.assigns.return_to)}
  end
end

token_registry/lib/token_registry_web/live/page_live.ex
defmodule TokenRegistryWeb.PageLive do
  use TokenRegistryWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, query: "", results: %{})}
  end

  @impl true
  def handle_event("suggest", %{"q" => query}, socket)   do
    if  length(query) > 4 do
    {:noreply, assign(socket, results: search(query), query: query)}
    else
      {:noreply, socket}
    end
  end

  @impl true
  def handle_event("search", %{"q" => query}, socket) do
    case search(query) do
      %{^query => vsn} ->
        {:noreply, redirect(socket, external: "https://hexdocs.pm/#{query}/#{vsn}")}

      _ ->
        {:noreply,
         socket
         |> put_flash(:error, "No dependencies found matching \"#{query}\"")
         |> assign(results: %{}, query: query)}
    end
  end

  defp search(query) do
    if not TokenRegistryWeb.Endpoint.config(:code_reloader) do
      raise "action disabled when not in development"
    end

    for {app, desc, vsn} <- Application.started_applications(),
        app = to_string(app),
        String.starts_with?(app, query) and not List.starts_with?(desc, ~c"ERTS"),
        into: %{},
        do: {app, vsn}
  end
end

token_registry/lib/token_registry_web/live/token_live/form_component.ex
defmodule TokenRegistryWeb.TokenLive.FormComponent do
  use TokenRegistryWeb, :live_component

  alias TokenRegistry.Registry




  @impl true
  def update(%{token: token} = assigns, socket) do
    changeset = Registry.change_token(token)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)
     |> allow_upload(:image,
              accept: ~w(.jpg .jpeg .png), max_entries: 1,
              auto_upload: true, progress: &handle_progress/3
              )
    }
  end

@impl Phoenix.LiveView
def handle_event("validate", _params, socket) do
  {:noreply, socket}
end


  # @impl true
  # def handle_event("validate", %{"token" => token_params}, socket) do
  #   changeset =
  #     socket.assigns.token
  #     |> Registry.change_token(token_params)
  #     |> Map.put(:action, :validate)

  #   {:noreply, assign(socket, :changeset, changeset)}
  # end

  def handle_event("save", %{"token" => token_params}, socket) do
    save_token(socket, socket.assigns.action, token_params)
  end

  defp save_token(socket, :edit, token_params ) do
    case Registry.update_token(socket.assigns.token, (process_token_params(token_params))) do
      {:ok, _token} ->
        {:noreply,
         socket
         |> put_flash(:info, "Token updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_token(socket, :new, token_params) do
    case Registry.create_token(process_token_params(token_params)) do
      {:ok, _token} ->
        {:noreply,
         socket
         |> put_flash(:info, "Token created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end

  defp process_token_params(%{"metadata" => metadata} = token_params) do
    token_params |> Map.put("metadata", Jason.decode!(metadata))
  end

  defp handle_progress(:image, entry, socket) do
      if entry.done? do
        path =
        consume_uploaded_entry(
          socket,entry,
          &upload_static_file(&1, socket)
        )
        {:noreply,
        socket
        |> put_flash(:info, "file #{entry.client_name} uploaded")
        |> update_changeset(:icon_upload, path)}
        else
          {:noreply, socket}
      end
    end

    def update_changeset(%{assigns: %{changeset: changeset}} = socket, key, value) do
      socket
      |> assign(:changeset, Ecto.Changeset.put_change(changeset, key, value))
    end

    defp upload_static_file(%{path: path}, socket) do
      # Plug in your production image file persistence implementation here!
      dest = Path.join("priv/static/images", Path.basename(path))
      File.cp!(path, dest)
      Routes.static_path(socket, "/images/#{Path.basename(dest)}")
    end

end

token_registry/lib/token_registry_web/live/token_live/index.ex
defmodule TokenRegistryWeb.TokenLive.Index do
  use TokenRegistryWeb, :live_view

  alias TokenRegistry.Registry
  alias TokenRegistry.Registry.Token

  @impl true
  def mount(_params, _session, socket) do
    {:ok,
    socket
    |> assign(:sort, "symbol.asc")
    |> assign(:pager, tokens_pager(socket, %{
      "sort" => "symbol.asc",
      "page" => "1",
    }))
    |> assign(query: "", results: %{})
    }
  end

  @impl true
  def handle_params(%{"sort" => sort, "page" => page} = params, url, socket) do
    IO.inspect({params, url, socket})
    {:noreply,
    apply_action(socket, socket.assigns.live_action, params)
    |> assign(:pager, tokens_pager(socket, params))
    }
  end
  @impl true
  def handle_params(_, url, socket) do
   handle_params(%{"sort" => "symbol.asc", "page" => "1"}, url, socket )
  end

  @impl true
  def handle_event("search", %{"search" => query}, socket) do
    {:noreply, assign(socket, :tokens, list_search(query))}
  end




  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Token")
    |> assign(:token, Registry.get_token!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Token")
    |> assign(:token, %Token{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Tokens")
    |> assign(:token, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    token = Registry.get_token!(id)
    {:ok, _} = Registry.delete_token(token)

    {:noreply, assign(socket, :tokens, list_tokens())}
  end

  defp list_tokens do
    Registry.list_tokens()
  end

  defp list_search( query) do
    Registry.search_tokens(query)
  end

  defp tokens_pager(socket, params) do
    if connected?(socket), do: Registry.paginate_tokens(params), else:  %Scrivener.Page{
      entries: [],
      page_number:  1,
      page_size: 0,
      total_entries: 0,
      total_pages:  0
    }
  end

  # def handle_params(params, _, socket) do
  #   IO.inspect({"handle_params", params})
  #   {:noreply,
  #    socket
  #   |> assign(:pager, tokens_pager(socket, params))
  #   }
  # end

  # def handle_params(_, _, socket) do
  #   IO.inspect({"handle_params", "_,_"})
  #   {:noreply, socket}
  # end

  def handle_event("nav", %{"page" => page} = params, socket) do
    IO.inspect({"nav", params, socket})

    {:noreply,
        socket
        |> assign(:page, page)
        |> push_patch( to: Routes.token_index_path(socket, :index, sort: socket.assigns.sort, page: page))
      }
  end

  def handle_event("sort", %{"sort" => sort} = params, socket) do
    socket =
      socket
      |> assign(:sort, sort)
      IO.inspect({"sort", params, socket})
    {:noreply,
      push_patch(socket, to: Routes.token_index_path(socket, :index, sort: sort, page: socket.assigns.page))
  }

  end



  # def handle_event("nav", params, socket) do

  #   {:noreply, live_redirect(socket, to: Routes.live_path(socket, ProductListLive, page: page))}

  #   pager = tokens_pager(socket, params)
  #   IO.inspect(pager)

  #   {:noreply,
  #   socket
  #   |> assign(:pager, pager)
  #   }

  #   # {:noreply, live_redirect(socket, to: Routes.live_path(socket, Index, page_number: page_number))}
  # end

end

token_registry/lib/token_registry_web/live/token_live/show.ex
defmodule TokenRegistryWeb.TokenLive.Show do
  use TokenRegistryWeb, :live_view

  alias TokenRegistry.Registry

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:token, Registry.get_token!(id))}
  end

  defp page_title(:show), do: "Show Token"
  defp page_title(:edit), do: "Edit Token"
end

token_registry/lib/token_registry_web/live/token_live/token_basic_component.ex
defmodule TokenRegistryWeb.TokenLive.TokenBasicComponent do
  use TokenRegistryWeb, :live_component

  alias TokenRegistry.Registry


  def update(assigns, socket) do
    {:ok,
     socket
     |> assign(assigns)
     |> assign_sparkline()}
  end


  defp assign_sparkline(%{assigns: %{token: token}} = socket) do
    socket
    |> assign(:chart, Contex.Sparkline.new([0, 5, 10, 15, 12, 12, 15, 14, 20, 14, 10, 15, 15]) |> Contex.Sparkline.draw() )
  end



end

token_registry/lib/token_registry_web/live/token_live/token_header_component.ex
defmodule TokenRegistryWeb.TokenLive.TokenHeaderComponent do
  use TokenRegistryWeb, :live_component

  alias TokenRegistry.Registry


  def update(assigns, socket) do
    {:ok,
     socket
     |> assign(assigns)
     |> assign_sparkline()}
  end


  defp assign_sparkline(%{assigns: %{token: token}} = socket) do
    socket
    |> assign(:chart, Contex.Sparkline.new([0, 5, 10, 15, 12, 12, 15, 14, 20, 14, 10, 15, 15]) |> Contex.Sparkline.draw() )
  end



end

token_registry/lib/token_registry_web/live/token_live/index.html.leex
<%= if @live_action in [:new, :edit] do %>
  <%= live_modal @socket, TokenRegistryWeb.TokenLive.FormComponent,
    id: @token.id || :new,
    title: @page_title,
    action: @live_action,
    token: @token,
    return_to: Routes.token_index_path(@socket, :index) %>
<% end %>



  <header class="bg-white shadow">
    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold text-gray-900">
        REGISTERED TOKENS
      </h1>
    </div>
  </header>
  <main>
    <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">

<div class="grid grid-cols-3 gap-4 g-white overflow-hidden shadow rounded-lg divide-y divide-gray-200">
  <div class="px-4 py-5 sm:px-6">
  <button type="submit" class="inline-flex items-center px-6 py-3 border border-transparent text-base font-medium rounded-full shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
 <%= live_patch "Register Your Token", to: Routes.token_index_path(@socket, :new) %>
</button>

  </div>
  <div class="px-4 py-5 sm:px-6">
    <div class="flex-1 px-2 flex justify-center lg:ml-6 lg:justify-end">
      <div class="max-w-lg w-full lg:max-w-xs">
        <label for="search" class="sr-only">Search</label>
        <div class="relative text-gray-400 focus-within:text-gray-600">
          <div class="pointer-events-none absolute inset-y-0 left-0 pl-3 flex items-center">
            <!-- Heroicon name: solid/search -->
            <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
            </svg>
          </div>
          <form  phx-submit="search">
          <input id="search" valyue="<%= @query %>" class="block w-full bg-white py-2 pl-10 pr-3 border border-transparent rounded-md leading-5 text-gray-900 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-indigo-600 focus:ring-white focus:border-white sm:text-sm" placeholder="Search" type="search" name="search" phx-disable-with="Searching...">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>



<!-- This example requires Tailwind CSS v2.0+ -->
<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">

 <%= live_component @socket,
           TokenRegistryWeb.TokenLive.TokenTableComponent,
                caller: Routes.token_index_path(@socket, :index),
                pager: @pager,
                sort: @sort %>

      </div>
    </div>
  </div>
</div>
</div>
</main>

token_registry/lib/token_registry_web/live/token_live/show.html.leex
 <div class="pb-5 border-b border-gray-200 sm:pb-0">



 <%= live_component @socket,
           TokenRegistryWeb.TokenLive.TokenTabComponent,
                token: @token %>

                <span><%= live_patch "Edit", to: Routes.token_show_path(@socket, :edit, @token), class: "button" %></span>
<span><%= live_redirect "Back", to: Routes.token_index_path(@socket, :index) %></span>


  <header class="bg-white shadow">
    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">

 <%= live_component @socket,
           TokenRegistryWeb.TokenLive.TokenBasicComponent,
                token: @token %>
 </div>

 </header>



  <main>
    <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
    <%= live_component @socket,
           TokenRegistryWeb.TokenLive.TokenChartComponent,
                token: @token %>
                </div>
    <div>


<%= if @live_action in [:edit] do %>
  <%= live_modal @socket, TokenRegistryWeb.TokenLive.FormComponent,
    id: @token.id,
    title: @page_title,
    action: @live_action,
    token: @token,
    return_to: Routes.token_show_path(@socket, :show, @token) %>
<% end %>





</div>


</div>

token_registry/lib/token_registry_web/live/token_live/token_basic_component.html.leex
<div class="grid grid-cols-2 gap-4">
  <div>
      <%= live_component @socket,
                TokenRegistryWeb.TokenLive.TokenHeaderComponent,
                      token: @token %>
</div>



  <div>
 <%= live_component @socket,
           TokenRegistryWeb.TokenLive.TokenTickerComponent,
                token: @token %>
  </div>
</div>

token_registry/lib/token_registry_web/live/token_live/token_chart_component.html.leex
 <%=  @chart %>

token_registry/lib/token_registry_web/live/token_live/token_header_component.html.leex
<div class="flex">
  <div class="mr-4 flex-shrink-0">
    <img class="h-10 w-10 rounded-full" src="<%= @token.icon_upload %>" alt="">
  </div>
  <div>
  <span class="text-2xl font-bold text-gray-900">
       <%= @token.name %> </span>
       <%= @token.symbol %>
    <p class="mt-1">
      Repudiandae sint consequuntur vel. Amet ut nobis explicabo numquam expedita quia omnis voluptatem. Minus quidem ipsam quia iusto.
    </p>
  </div>
</div>

token_registry/lib/token_registry_web/live/token_live/token_row_component.html.leex
<tr id="token-<%= @token.id %>">
    <td class="px-6 py-4 whitespace-nowrap">
    <div class="flex items-center">
        <div class="flex-shrink-0 h-10 w-10">

        <img class="h-10 w-10 rounded-full" src="<%= if @token.icon_upload == nil, do: "/images/default_icon.png", else: @token.icon_upload  %>" alt="">
        </div>
        <div class="ml-4">
        <div class="text-sm font-medium text-gray-900">
            <%= live_redirect @token.symbol, to: Routes.token_show_path(@socket, :show, @token) %>
        </div>
        </div>
    </div>
    </td>
    <td class="px-6 py-4 whitespace-nowrap">
    <div class="text-sm text-gray-900"><%= @token.name %></div>
    </td>
    <td class="px-6 py-4 whitespace-nowrap">
    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
       <%= if Map.get(@metadata, "supply") == 0, do: 0, else:  Map.get(@metadata, "stake") / Map.get(@metadata, "supply") %>
    </span>
    </td>

    <td class="px-6 py-4 whitespace-nowrap">
    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
        <%= if Map.get(@metadata, "supply") == 0, do: 0, else:  Map.get(@metadata, "supply") * 38.71 %>
    </span>
    </td>
    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
    <%= Map.get(@metadata, "supply") %>
    </td>
    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
    <%=  @chart %>
    </td>

</tr>

token_registry/lib/token_registry_web/live/token_live/token_table_column_component.html.leex
<a class="px-2 py-2" href="#" phx-click="sort" phx-value-sort="<%= if @sort == @field <> ".asc", do: @field <> ".desc", else: @field <> ".asc" %>"><%= @name %></a>

token_registry/lib/token_registry_web/live/token_live/token_ticker_component.html.leex
<div class="flex">
  <div class="mr-4 flex-shrink-0">
  <div>
      <span class="text-2xl font-bold text-gray-900"><%= @price %></span>
      <span class="inline-flex items-center px-3 py-0.5 rounded-full text-sm font-medium bg-green-100 text-green-800">
  &Hat;<%= @pchg %>
</span>

 <%=  @sparkline %>
<div>high: <%= @hi %>
<div>low: <%= @lo %>
</div>
</div>
</div>